controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_api_v1:
    prefix: /api/v1
    resource: '@ApiBundle/Resources/config/routes.yaml'
