lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    token_ttl: 3600 # in seconds, default is 3600
    blocklist_token:
        enabled: false
        cache: cache.app
    api_platform:
        enabled: true
        check_path: /api/v1/auth
        username_path: username
        password_path: password