lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    token_ttl: 900 # in seconds, default is 15 minutes
    blocklist_token:
        enabled: true
        cache: cache.app
    api_platform:
        enabled: true
        check_path: /api/v1/auth
        username_path: username
        password_path: password
    token_extractors:
        authorization_header:
            enabled: true
            prefix: Bearer
            name: Authorization
    encoder:
        service: core.jwt_authentication.encoder
        signature_algorithm: RS256
        crypto_engine: openssl
